# Generated by Django 2.2.6 on 2019-10-08 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=255)),
                ('base', models.CharField(choices=[('CHOCOLATE', 'Chocolate'), ('VANILLA', 'Vanilla')], default='VANILLA', max_length=255)),
                ('available', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('SEASONAL', 'Seasonal')], default='WEEKLY', max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('date_churned', models.DateField(default=datetime.date.today, verbose_name='Date Churned')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
