# Generated by Django 2.2.6 on 2019-10-07 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream_text', models.CharField(max_length=255)),
                ('churned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date Churned')),
            ],
        ),
    ]
