# Generated by Django 2.2.6 on 2019-10-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('votes', models.IntegerField(default=0)),
                ('ice_cream_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream.Icecream')),
            ],
        ),
    ]
