# Generated by Django 2.2.6 on 2019-10-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='ice_cream_text',
            new_name='Section',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
