# Generated by Django 2.2.6 on 2019-10-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20191007_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Section',
            new_name='section',
        ),
    ]
