# Generated by Django 2.2.6 on 2019-10-07 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_auto_20191007_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='churned_date',
        ),
        migrations.AddField(
            model_name='choice',
            name='churned_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date Churned'),
        ),
    ]
